#include "DisasmbleTable.h"

int w, d;
DWORD Const;
DWORD EmulReadError;
PDWORD Parametr[2];

DWORD  SReg[6] = { DefaultES, DefaultCS, DefaultSS, DefaultDS, DefaultFS, DefaultGS};
//0   1   2   3   4   5
//ES, CS, SS, DS, FS, GS
union Regis  Reg[8]={ DefaultEAX, DefaultECX, DefaultEDX, DefaultEBX, DefaultESP, DefaultEBP, DefaultESI, DefaultEDI};
//  0      1      2      3      4      5      6      7
//"EAX", "ECX", "EDX", "EBX", "ESP", "EBP", "ESI", "EDI"

const struct  CTable Table[]={
//00
    {ID_ADD,   ID_METOD0}, 
    {ID_ADD,   ID_METOD0}, 
    {ID_ADD,   ID_METOD0}, 
    {ID_ADD,   ID_METOD0}, 
    {ID_ADD,   ID_METOD1}, 
    {ID_ADD,   ID_METOD1}, 
    {ID_PUSH,  ID_METOD3}, 
    {ID_POP,   ID_METOD3}, 
//08
    {ID_OR,    ID_METOD0}, 
    {ID_OR,    ID_METOD0}, 
    {ID_OR,    ID_METOD0}, 
    {ID_OR,    ID_METOD0}, 
    {ID_OR,    ID_METOD1}, 
    {ID_OR,    ID_METOD1}, 
    {ID_PUSH,  ID_METOD3}, 
    {ID_GROUP, ID_GROUP }, 
//10
    {ID_ADC,   ID_METOD0}, 
    {ID_ADC,   ID_METOD0}, 
    {ID_ADC,   ID_METOD0}, 
    {ID_ADC,   ID_METOD0}, 
    {ID_ADC,   ID_METOD1}, 
    {ID_ADC,   ID_METOD1}, 
    {ID_PUSH,  ID_METOD3}, 
    {ID_POP,   ID_METOD3}, 
//18
    {ID_SBB,   ID_METOD0}, 
    {ID_SBB,   ID_METOD0}, 
    {ID_SBB,   ID_METOD0}, 
    {ID_SBB,   ID_METOD0}, 
    {ID_SBB,   ID_METOD1}, 
    {ID_SBB,   ID_METOD1}, 
    {ID_PUSH,  ID_METOD3}, 
    {ID_POP,   ID_METOD3}, 
//20
    {ID_AND,   ID_METOD0}, 
    {ID_AND,   ID_METOD0}, 
    {ID_AND,   ID_METOD0}, 
    {ID_AND,   ID_METOD0}, 
    {ID_AND,   ID_METOD1}, 
    {ID_AND,   ID_METOD1}, 
    {ID_ES,    ID_PREFIX}, 
    {ID_DAA,   ID_METOD4}, 
//28
    {ID_SUB,   ID_METOD0}, 
    {ID_SUB,   ID_METOD0}, 
    {ID_SUB,   ID_METOD0}, 
    {ID_SUB,   ID_METOD0}, 
    {ID_SUB,   ID_METOD1}, 
    {ID_SUB,   ID_METOD1}, 
    {ID_CS,    ID_PREFIX}, 
    {ID_DAS,   ID_METOD4}, 
//30
    {ID_XOR,   ID_METOD0}, 
    {ID_XOR,   ID_METOD0}, 
    {ID_XOR,   ID_METOD0}, 
    {ID_XOR,   ID_METOD0}, 
    {ID_XOR,   ID_METOD1}, 
    {ID_XOR,   ID_METOD1}, 
    {ID_SS,    ID_PREFIX}, 
    {ID_AAA,   ID_METOD4}, 
//38
    {ID_CMP,   ID_METOD0}, 
    {ID_CMP,   ID_METOD0}, 
    {ID_CMP,   ID_METOD0}, 
    {ID_CMP,   ID_METOD0}, 
    {ID_CMP,   ID_METOD1}, 
    {ID_CMP,   ID_METOD1}, 
    {ID_DS,    ID_PREFIX}, 
    {ID_AAS,   ID_METOD4}, 
//40
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
    {ID_INC,   ID_METOD2}, 
//48
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
    {ID_DEC, ID_METOD2}, 
//50
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
    {ID_PUSH, ID_METOD2}, 
//58
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
    {ID_POP, ID_METOD2}, 
//60
    {ID_PUSHA,  ID_METOD4}, 
    {ID_POPA,   ID_METOD4}, 
    {ID_BOUND,  ID_METOD0}, 
    {ID_ARPL,   ID_METOD0}, 
    {ID_FS,     ID_PREFIX}, 
    {ID_GS,     ID_PREFIX}, 
    {ID_OPSIZE, ID_PREFIX}, 
    {ID_ADDR,   ID_PREFIX}, 
//68
    {ID_PUSH,  ID_METOD5}, 
    {ID_IIMUL, ID_METOD6}, 
    {ID_PUSH,  ID_METOD5}, 
    {ID_IIMUL, ID_METOD6}, 
    {ID_INSB,  ID_METOD4}, 
    {ID_INSW,  ID_METOD4}, 
    {ID_OUTSB, ID_METOD4}, 
    {ID_OUTSW, ID_METOD4}, 
//70
    {ID_JO,  ID_METOD5}, 
    {ID_JNO, ID_METOD5}, 
    {ID_JC,  ID_METOD5}, 
    {ID_JNC, ID_METOD5}, 
    {ID_JZ,  ID_METOD5}, 
    {ID_JNZ, ID_METOD5}, 
    {ID_JBE, ID_METOD5}, 
    {ID_JA,  ID_METOD5}, 
//78
    {ID_JS,  ID_METOD5}, 
    {ID_JNS, ID_METOD5}, 
    {ID_JPE, ID_METOD5}, 
    {ID_JPO, ID_METOD5}, 
    {ID_JL,  ID_METOD5}, 
    {ID_JNL, ID_METOD5}, 
    {ID_JNG, ID_METOD5}, 
    {ID_JG,  ID_METOD5}, 
//80
    {ID_IMMEDIATE, ID_IMMEDIATE}, 
    {ID_IMMEDIATE, ID_IMMEDIATE}, 
    {ID_IMMEDIATE, ID_IMMEDIATE}, 
    {ID_IMMEDIATE, ID_IMMEDIATE}, 
    {ID_TEST, ID_METOD0}, 
    {ID_TEST, ID_METOD0}, 
    {ID_XCHG, ID_METOD0}, 
    {ID_XCHG, ID_METOD0}, 
//88
    {ID_MOV, ID_METOD0}, 
    {ID_MOV, ID_METOD0}, 
    {ID_MOV, ID_METOD0}, 
    {ID_MOV, ID_METOD0}, 
    {ID_MOV, ID_METOD3}, 
    {ID_LEA, ID_METOD0}, 
    {ID_MOV, ID_METOD3}, 
    {ID_POP, ID_METOD0}, 
//90
    {ID_NOP, ID_METOD4}, 
    {ID_XCHG, ID_METOD2}, 
    {ID_XCHG, ID_METOD2}, 
    {ID_XCHG, ID_METOD2}, 
    {ID_XCHG, ID_METOD2}, 
    {ID_XCHG, ID_METOD2}, 
    {ID_XCHG, ID_METOD2}, 
    {ID_XCHG, ID_METOD2}, 
//98
    {ID_CBW,   ID_METOD4}, 
    {ID_CWD,   ID_METOD4}, 
    {ID_CALL,  ID_METOD5}, 
    {ID_WAIT,  ID_METOD4}, 
    {ID_PUSHF, ID_METOD4}, 
    {ID_POPF,  ID_METOD4}, 
    {ID_SAHF,  ID_METOD4}, 
    {ID_LAHF,  ID_METOD4}, 
//A0
    {ID_MOV,   ID_METOD1}, 
    {ID_MOV,   ID_METOD1}, 
    {ID_MOV,   ID_METOD1}, 
    {ID_MOV,   ID_METOD1}, 
    {ID_MOVSB, ID_METOD4}, 
    {ID_MOVSW, ID_METOD4}, 
    {ID_CMPSB, ID_METOD4}, 
    {ID_CMPSW, ID_METOD4}, 
//A8
    {ID_TEST,  ID_METOD1}, 
    {ID_TEST,  ID_METOD1}, 
    {ID_SOTSB, ID_METOD4}, 
    {ID_SOTS,  ID_METOD4}, 
    {ID_LODSB, ID_METOD4}, 
    {ID_LODS,  ID_METOD4}, 
    {ID_SCASB, ID_METOD4}, 
    {ID_SCAS,  ID_METOD4}, 
//B0
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
//B8
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
    {ID_MOV, ID_METOD2}, 
//C0
    {ID_SHIFT, ID_SHIFT }, 
    {ID_SHIFT, ID_SHIFT }, 
    {ID_RET,   ID_METOD5}, 
    {ID_RET,   ID_METOD4}, 
    {ID_LES,   ID_METOD0}, 
    {ID_LDS,   ID_METOD0}, 
    {ID_MOV,   ID_METOD0}, 
    {ID_MOV,   ID_METOD0}, 
//C8
    {ID_ENTER, ID_METOD4}, 
    {ID_LEAVE, ID_METOD4}, 
    {ID_RETF,  ID_METOD5}, ///
    {ID_RETF,  ID_METOD4}, ///
    {ID_BKPT,  ID_METOD4}, 
    {ID_INT,   ID_METOD5}, 
    {ID_INTO,  ID_METOD4}, 
    {ID_IRET,  ID_METOD4}, 
//D0
    {ID_SHIFT, ID_SHIFT }, 
    {ID_SHIFT, ID_SHIFT }, 
    {ID_SHIFT,  ID_SHIFT }, 
    {ID_SHIFT,  ID_SHIFT }, 
    {ID_AAM,    ID_METOD4}, 
    {ID_AAD,    ID_METOD4}, 
    {ID_SETALC, ID_METOD4}, 
    {ID_XLAT,   ID_METOD4}, 
//D8
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
    {ID_ESC,    ID_METOD8}, 
//E0
    {ID_LOOPNZ, ID_METOD5}, 
    {ID_LOOPZ,  ID_METOD5}, 
    {ID_LOOP,   ID_METOD5}, 
    {ID_JCXZ,   ID_METOD5}, 
    {ID_IN,     ID_METOD1}, 
    {ID_IN,     ID_METOD1}, 
    {ID_OUT,    ID_METOD1}, 
    {ID_OUT,    ID_METOD1}, 
//E8
    {ID_CALL,   ID_METOD5}, 
    {ID_JMP,    ID_METOD5}, 
    {ID_JMP,    ID_METOD5}, 
    {ID_JMP,    ID_METOD5}, 
    {ID_IN,     ID_METOD1}, 
    {ID_IN,     ID_METOD1}, 
    {ID_OUT,    ID_METOD1}, 
    {ID_OUT,    ID_METOD1}, 
//F0
    {ID_LOCK,   ID_PREFIX}, 
    {ID_SMI,    ID_METOD4}, 
    {ID_REPNZ,  ID_PREFIX}, 
    {ID_REPZ,   ID_PREFIX}, 
    {ID_HLT,    ID_METOD4}, 
    {ID_CMC,    ID_METOD4}, 
    {ID_GRP1,   ID_GRP1  }, 
    {ID_GRP1,   ID_GRP1  }, 
//F8
    {ID_CLC,    ID_METOD4}, 
    {ID_STC,    ID_METOD4}, 
    {ID_CLI,    ID_METOD4}, 
    {ID_STI,    ID_METOD4}, 
    {ID_CLD,    ID_METOD4}, 
    {ID_STD,    ID_METOD4}, 
    {ID_GRP2,   ID_GRP2  }, 
    {ID_GRP2,   ID_GRP2  }
};

//////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////

short int TableALL[][8]=
{
/*ALL0 80*/{ID_ADD,  ID_OR,   ID_ADC,  ID_SBB,  ID_AND, ID_SUB,  ID_XOR, ID_CMP }, 
/*ALL1 C0*/{ID_ROL,  ID_ROR,  ID_RCL,  ID_RCR,  ID_SHL, ID_SHR,  ID_SAL, ID_SAR }, 
/*ALL2 F6*/{ID_TEST, ID_TEST, ID_NOT,  ID_NEG,  ID_MUL, ID_IMUL, ID_DIV, ID_IDIV}, 
/*ALL3 FE*/{ID_INC,  ID_DEC,  ID_CALL, ID_CALL, ID_JMP, ID_JMP,  ID_PUSH, -7}
};

const struct  CTable Table0F[]=
{
//00
    {ID_Grp1,  ID_Grp1  }, 
    {ID_Grp2,  ID_Grp2  }, 
    {ID_LAR,   ID_METOD0}, 
    {ID_LSL,   ID_METOD0}, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_CLTS,  ID_METOD4}, 
    {ID_ERORR, ID_ERORR }, 
//08
    {ID_INVD, ID_METOD4}, 
    {ID_WBINVD, ID_METOD4}, 
    {ID_ERORR, ID_ERORR }, 
    {ID_UD2, ID_METOD4}, 
    {ID_ERORR, ID_ERORR }, 
    {ID_PREFETCH, ID_ERORR}, 
    {ID_FEMMS, ID_METOD4}, 
    {ID_ERORR, ID_ERORR }, 
//10
    {ID_MOVUPS, ID_METOD0}, //
    {ID_MOVUPS, ID_METOD0}, //
    {ID_MOVLPS, ID_METOD0}, //
    {ID_MOVLPS, ID_METOD0}, //
    {ID_UNPCKLPS, ID_METOD0}, //
    {ID_UNPCKHPS, ID_METOD0}, //
    {ID_MOVHPS, ID_METOD0}, //
    {ID_MOVHPS, ID_METOD0}, //
//18
    {ID_Grp3, ID_METOD0}, //ID_Grp3
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_NOP, ID_ERORR }, 
//20
    {ID_MOV_, ID_METOD0}, //
    {ID_MOV_, ID_METOD0}, //
    {ID_MOV_, ID_METOD0}, //
    {ID_MOV_, ID_METOD0}, //
    {ID_MOV, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_MOV, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
//28
    {ID_MOVAP, ID_METOD0}, 
    {ID_MOVAP, ID_METOD0}, 
    {ID_CVTPI2, ID_METOD0}, 
    {ID_MOVNTP, ID_ERORR }, 
    {ID_CVTT, ID_METOD0}, 
    {ID_CVT, ID_METOD0}, 
    {ID_UCOMIS, ID_METOD0}, 
    {ID_COMIS, ID_METOD0}, 
//30
    {ID_WRMSR, ID_METOD4}, 
    {ID_RDTSC, ID_METOD4}, 
    {ID_RDMSR, ID_METOD4}, 
    {ID_RDPMC, ID_METOD4}, 
    {ID_SYSENTER, ID_METOD4}, 
    {ID_SYSENTER, ID_METOD4}, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
//38
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
//40
    {ID_CMOVO, ID_METOD0}, 
    {ID_CMOVNO, ID_METOD0}, 
    {ID_CMOVC, ID_METOD0}, 
    {ID_CMOVNC, ID_METOD0}, 
    {ID_CMOVZ, ID_METOD0}, 
    {ID_CMOVNZ, ID_METOD0}, 
    {ID_CMOVBE, ID_METOD0}, 
    {ID_CMOVA, ID_METOD0}, 
//48
    {ID_CMOVS, ID_METOD0}, 
    {ID_CMOVNS, ID_METOD0}, 
    {ID_CMOVPE, ID_METOD0}, 
    {ID_CMOVPO, ID_METOD0}, 
    {ID_CMOVL, ID_METOD0}, 
    {ID_CMOVNL, ID_METOD0}, 
    {ID_CMOVNG, ID_METOD0}, 
    {ID_CMOVG, ID_METOD0}, 
//50
    {ID_MOVMSK, ID_ERORR }, 
    {ID_SQRT, ID_METOD0}, 
    {ID_RSQRT, ID_METOD0}, 
    {ID_RCP, ID_METOD0}, 
    {ID_AND, ID_METOD0}, 
    {ID_ANDN, ID_METOD0}, 
    {ID_OR, ID_METOD0}, 
    {ID_XOR, ID_METOD0}, 
//58
    {ID_ADD, ID_METOD0}, 
    {ID_MUL, ID_METOD0}, 
    {ID_CVT, ID_ERORR }, 
    {ID_CVT, ID_ERORR }, 
    {ID_SUB, ID_METOD0}, 
    {ID_MIN, ID_METOD0}, 
    {ID_DIV, ID_METOD0}, 
    {ID_MAX, ID_METOD0}, 
//60
    {ID_PUNPCKLBW, ID_METOD0}, 
    {ID_PUNPCKLWD, ID_METOD0}, 
    {ID_PUNPCKLDQ, ID_METOD0}, 
    {ID_PACKSSWB, ID_METOD0}, 
    {ID_PCMPGTB, ID_METOD0}, 
    {ID_PCMPGTW, ID_METOD0}, 
    {ID_PCMPGTD, ID_METOD0}, 
    {ID_PACKUSWB, ID_METOD0}, 
//68
    {ID_PUNPCKHBW, ID_METOD0}, 
    {ID_PUNPCKHWD, ID_METOD0}, 
    {ID_PUNPCKHDQ, ID_METOD0}, 
    {ID_PACKSSDW, ID_METOD0}, 
    {ID_PUNPCKLQDQ, ID_ERORR }, 
    {ID_PUNPCKHQDQ, ID_ERORR }, 
    {ID_MOVD, ID_METOD0}, 
    {ID_MOV, ID_METOD0}, 
//70
    {ID_PSHUF, ID_METOD7}, 
    {ID_Grp4, ID_ERORR }, 
    {ID_Grp5, ID_ERORR }, 
    {ID_Grp6, ID_ERORR }, 
    {ID_PCMPEQB, ID_METOD0}, 
    {ID_PCMPEQW, ID_METOD0}, 
    {ID_PCMPEQQ, ID_METOD0}, 
    {ID_EMMS, ID_METOD4}, 
//78
    {ID_MMX_UD, ID_ERORR }, 
    {ID_MMX_UD, ID_ERORR }, 
    {ID_MMX_UD, ID_ERORR }, 
    {ID_MMX_UD, ID_ERORR }, 
    {ID_HADDPD, ID_ERORR }, 
    {ID_HSUBPD, ID_ERORR }, 
    {ID_MOVD, ID_METOD0}, 
    {ID_MOV, ID_METOD0}, 
//80
    {ID_JO, ID_METOD5}, 
    {ID_JNO, ID_METOD5}, 
    {ID_JC, ID_METOD5}, 
    {ID_JNC, ID_METOD5}, 
    {ID_JZ, ID_METOD5}, 
    {ID_JNZ, ID_METOD5}, 
    {ID_JBE, ID_METOD5}, 
    {ID_JA, ID_METOD5}, 
//88
    {ID_JS, ID_METOD5}, 
    {ID_JNS, ID_METOD5}, 
    {ID_JPE, ID_METOD5}, 
    {ID_JPO, ID_METOD5}, 
    {ID_JL, ID_METOD5}, 
    {ID_JNL, ID_METOD5}, 
    {ID_JNG, ID_METOD5}, 
    {ID_JG, ID_METOD5}, 
//90
    {ID_SETO, ID_METOD0}, 
    {ID_SETNO, ID_METOD0}, 
    {ID_SETC, ID_METOD0}, 
    {ID_SETNC, ID_METOD0}, 
    {ID_SETZ, ID_METOD0}, 
    {ID_SETNZ, ID_METOD0}, 
    {ID_SETBE, ID_METOD0}, 
    {ID_SETA, ID_METOD0}, 
//98
    {ID_SETS, ID_METOD0}, 
    {ID_SETNS, ID_METOD0}, 
    {ID_SETPE, ID_METOD0}, 
    {ID_SETPO, ID_METOD0}, 
    {ID_SETL, ID_METOD0}, 
    {ID_SETNL, ID_METOD0}, 
    {ID_SETNG, ID_METOD0}, 
    {ID_SETG, ID_METOD0}, 
//A0
    {ID_PUSH, ID_METOD3}, 
    {ID_POP, ID_METOD3}, 
    {ID_CPUID, ID_METOD4}, 
    {ID_BT, ID_METOD0}, 
    {ID_SHLD, ID_METOD7}, 
    {ID_SHLD, ID_METOD0}, 
    {ID_ERORR, ID_ERORR }, 
    {ID_ERORR, ID_ERORR }, 
//A8
    {ID_PUSH, ID_METOD3}, 
    {ID_POP, ID_METOD3}, 
    {ID_RSM, ID_METOD4}, 
    {ID_BTS, ID_METOD0}, 
    {ID_SHRD, ID_METOD7}, 
    {ID_SHRD, ID_METOD0}, 
    {ID_Grp7, ID_METOD0}, 
    {ID_IMUL2, ID_METOD0}, 
//B0
    {ID_CMPXCHG, ID_METOD0}, 
    {ID_CMPXCHG, ID_METOD0}, 
    {ID_LSS, ID_METOD0}, 
    {ID_BTR, ID_METOD0}, 
    {ID_LFS, ID_METOD0}, 
    {ID_LGS, ID_METOD0}, 
    {ID_MOVZX, ID_METOD0}, 
    {ID_MOVZX, ID_METOD0}, 
//B8
    {ID_ERORR, ID_ERORR }, 
    {ID_Grp8, ID_ERORR }, 
    {ID_Grp9, ID_Grp9  }, 
    {ID_BTC, ID_METOD0}, 
    {ID_BSF, ID_METOD0}, 
    {ID_BSR, ID_METOD0}, 
    {ID_MOVSX, ID_METOD0}, 
    {ID_MOVSX, ID_METOD0}, 
//C0
    {ID_XADD, ID_METOD0}, 
    {ID_XADD, ID_METOD0}, 
    {ID_CMP, ID_METOD7}, 
    {ID_MOVNTI, ID_ERORR }, 
    {ID_PINSRW, ID_METOD7}, 
    {ID_PEXTRW, ID_METOD7}, 
    {ID_SHUFP, ID_METOD7}, 
    {ID_Grp10, ID_ERORR }, 
//C8
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
    {ID_BSWAP, ID_METOD4}, 
//D0
    {ID_ADDSUB, ID_ERORR }, 
    {ID_PSRLW, ID_METOD0}, 
    {ID_PSRLD, ID_METOD0}, 
    {ID_PSRLQ, ID_METOD0}, 
    {ID_PADDQ, ID_ERORR }, 
    {ID_PMULLW, ID_METOD0}, 
    {ID_MOV, ID_ERORR }, 
    {ID_PMOVMSKB, ID_METOD0}, 
//D8
    {ID_PSUBUSB, ID_METOD0}, 
    {ID_PSUBUSW, ID_METOD0}, 
    {ID_PMINUB, ID_METOD0}, 
    {ID_PADND, ID_METOD0}, 
    {ID_PADDUSB, ID_METOD0}, 
    {ID_PADDUSW, ID_METOD0}, 
    {ID_PMAXUB, ID_METOD0}, 
    {ID_PANDN, ID_METOD0}, 
//E0
    {ID_PAVGB, ID_METOD0}, 
    {ID_PSRAW, ID_METOD0}, 
    {ID_PSRAD, ID_METOD0}, 
    {ID_PSRAQ, ID_METOD0}, 
    {ID_PMULHUW, ID_METOD0}, 
    {ID_PMULHW, ID_METOD0}, 
    {ID_CVT, ID_ERORR }, 
    {ID_MOVNTQ, ID_METOD0}, 
//E8
    {ID_PSUBSB, ID_METOD0}, 
    {ID_PSUBSW, ID_METOD0}, 
    {ID_PMINSW, ID_METOD0}, 
    {ID_POR, ID_METOD0}, 
    {ID_PADDSB, ID_METOD0}, 
    {ID_PADDSW, ID_METOD0}, 
    {ID_PMAXSW, ID_METOD0}, 
    {ID_PXOR, ID_METOD0}, 
//F0
    {ID_LDDQU, ID_ERORR }, 
    {ID_PSLLW, ID_METOD0}, 
    {ID_PSLLD, ID_METOD0}, 
    {ID_PSLLQ, ID_METOD0}, 
    {ID_PMULUDQ, ID_ERORR }, 
    {ID_PMADDWD, ID_METOD0}, 
    {ID_PSADBW, ID_METOD0}, 
    {ID_MASKMOVQ, ID_METOD0}, 
//F8
    {ID_PSUBB, ID_METOD0}, 
    {ID_PSUBW, ID_METOD0}, 
    {ID_PSUBD, ID_METOD0}, 
    {ID_PSUBQ, ID_ERORR }, 
    {ID_PADDB, ID_METOD0}, 
    {ID_PADDW, ID_METOD0}, 
    {ID_PADDD, ID_METOD0}, 
    {ID_ERORR, ID_ERORR }
};
//0F
short int GroupTable[][8]=
{
/*Group 0*/{ID_SLDT, ID_STR, ID_LLDT, ID_LTR, ID_VERR, ID_VERW, ID_ERORR, ID_ERORR }, 
/*Group 1*/{ID_SGDT, ID_SIDT, ID_LGDT, ID_LIDT, ID_SMSW, ID_INVLPG, ID_LMSW, ID_INVLPG}, 
/*Group 2*/{ID_PREFTCHINTA, ID_PREFTCH0, ID_PREFTCH1, ID_PREFTCH2, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR }, 
/*Group 3*/{ID_ERORR, ID_ERORR, ID_PSRLW, ID_ERORR, ID_PSRAW, ID_ERORR, ID_PSLLW, ID_ERORR}, 
/*Group 4*/{ID_ERORR, ID_ERORR, ID_PSRLD, ID_ERORR, ID_PSRAD, ID_ERORR, ID_PSLLD, ID_ERORR}, 
/*Group 5*/{ID_ERORR, ID_ERORR, ID_PSRLQ, ID_ERORR, ID_PSRAQ, ID_ERORR, ID_PSLLQ, ID_ERORR}, 
/*Group 6*/{ID_FXSAVE, ID_FXRSTOR, ID_LDMXCSR, ID_STMXCSR, ID_ERORR, ID_LFENCE, ID_MFENCE, ID_SFENCE}, 
/*Group 7*/{ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR}, 
/*Group 8*/{ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_BT, ID_BTS, ID_BTR, ID_BTC}, 
/*Group 9*/{ID_ERORR, ID_CMPXCH8B, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR, ID_ERORR}, 
};